# Generated by Django 4.1.6 on 2023-03-08 09:38

import django.core.validators
from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dairyapp', '0013_auto_20200519_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='address',
            field=encrypted_model_fields.fields.EncryptedTextField(default='Anonymous'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='managername',
            field=encrypted_model_fields.fields.EncryptedTextField(default='Anonymous'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendorcontact',
            field=encrypted_model_fields.fields.EncryptedIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999999999)]),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendorname',
            field=encrypted_model_fields.fields.EncryptedTextField(default='Anonymous'),
        ),
    ]
